channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - lightgbm
  - matplotlib
  - scipy
  - numpy
  - pandas
  - requests
  - numexpr
  - bokeh
  - seaborn
  - pillow
  - ipywidgets
  - altair
  - bokeh
  - plotly
  - keras
  - pymc3
  - graphviz
  - python-graphviz
  - pydot
  - mkl-service
  - pip:
    - corner
    - keract
    - tf-nightly-2.0-preview
    - umap-learn
