channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - scipy
  - numpy
  - pandas
  - numexpr
  - bokeh
  - seaborn
  - pillow
  - ipywidgets
  - altair
  - plotly
  - keras
  - pymc3
  - pip:
    - corner
